discretization:
  cart_space:
    start: -2.4
    end: 2.4
    bins: 10
  cart_vel:
    start: -4
    end: 4
    bins: 10
  pole_space:
    start: -0.2095
    end: 0.2095
    bins: 10
  pole_vel:
    start: -4
    end: 4
    bins: 10

training:
  learning_rate: 0.15
  discount_factor: 0.99
  epsilon_start: 1.0
  epsilon_rate: 0.0001
  epsilon_min: 0.01
  max_rewards: 200

logging:
  rewards_episode: []
